# Generated by Django 5.0.1 on 2024-06-09 14:26

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=254, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создан')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Изменен')),
                ('headline', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Заголовок')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(50)], verbose_name='Содержание')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
