# Generated by Django 5.0.1 on 2024-06-09 14:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import products.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=254, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создан')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Название')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Описание')),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес, г.')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Базовая цена, руб.')),
                ('new_price', models.FloatField(default=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Базовая цена, руб.'), editable=False, verbose_name='Цена с учетом скидки/надбавки, руб.')),
                ('discount', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Скидка, %')),
                ('discount_rub', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Скидка, руб.')),
                ('increment', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Надбавка в процентах')),
                ('increment_rub', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Надбавка в рублях')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество, шт.')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('sticker', models.CharField(choices=[('NEW', 'Новинка'), ('SAL', 'Скидка'), ('TOP', 'Топ продаж'), ('ETY', 'Без отметки')], default='NEW', max_length=3, verbose_name='Наклейка')),
                ('category', models.ManyToManyField(related_name='products', to='products.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создан')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.services.get_image_path, verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
