# Generated by Django 5.0.1 on 2024-05-24 23:19

import company.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator('1950-01-01')], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11), company.validators.phone_number_validator], verbose_name='Номер телефона: +'),
        ),
    ]
