# Generated by Django 5.0.1 on 2024-05-26 08:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_alter_customuser_phone_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1950, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2006, 5, 26))], verbose_name='Дата рождения'),
        ),
    ]
