# Generated by Django 5.0.1 on 2024-01-06 16:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Название')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Описание')),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес, г.')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена, руб.')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество, шт.')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('category', models.ManyToManyField(related_name='products', to='products.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('data', models.ImageField(blank=True, null=True, upload_to=products.models.get_image_path)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
