# Generated by Django 5.0.1 on 2024-05-23 23:47

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(choices=[('DIR', 'Директор'), ('ADM', 'Администратор'), ('MNR', 'Менеджер'), ('CCK', 'Повар'), ('CAS', 'Кассир'), ('DRV', 'Водитель'), ('CUR', 'Курьер')], default='CAS', max_length=3, verbose_name='Должность')),
                ('contract', models.CharField(max_length=32, unique=True, verbose_name='Номер трудового договора')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('sign.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
