# Generated by Django 5.0.1 on 2024-05-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('DIR', 'Директор'), ('ADM', 'Администратор'), ('MNR', 'Менеджер'), ('CCK', 'Повар'), ('CAS', 'Кассир'), ('DRV', 'Водитель'), ('CUR', 'Курьер')], default='MNR', max_length=3, verbose_name='Должность'),
        ),
    ]
